### ISSUE TITLE
加载 PHP 扩展失败

### ISSUE THREAD

**Issue by Sligcm** [SeasX/SeasSnowflake#11]
示例里是：
extension=seassnowflake.so
会报错误：
PHP Warning:  PHP Startup: Unable to load dynamic library 'seassnowflake.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/seassnowflake.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902/seassnowflake.so: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20190902/seassnowflake.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902/seassnowflake.so.so: No such file or directory)) in Unknown on line 0
实际需要修改为：
extension=SeasSnowflake.so
才会正常可用。

**Comment by Rock-520** [comment]
fixed!
